apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: DB_DATABASE
              value: mydatabase
            - name: DB_HOST
              value: mysql_db
            - name: DB_PWD
              value: Password.1
            - name: DB_USER
              value: willy
          image: willywan/3tierbackend:v1.0
          name: backend
          ports:
            - containerPort: 4000
              protocol: TCP
      restartPolicy: Always
