name: Release from PR
on:
  pull_request:
    types:
      - closed

permissions:
  contents: write  # Required for pushing tags and creating releases

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extract PR Information
        id: parse_pr
        env:
          PR_TITLE: "${{ github.event.pull_request.title }}"
          PR_BODY: "${{ github.event.pull_request.body }}"
        run: |
          # Extract version number and title from PR title
          if [[ "$PR_TITLE" =~ Release[[:space:]]([0-9]+\.[0-9]+):[[:space:]](.*) ]]; then
            VERSION="${BASH_REMATCH[1]}"
            FEATURE_TITLE="${BASH_REMATCH[2]}"
          else
            VERSION="0.0.1"
            FEATURE_TITLE="Production Update"
          fi

          # Extract "What's New" section from PR body
          WHATS_NEW=$(echo "$PR_BODY" | awk '/## What'\''s New/{flag=1; next} /## /{flag=0} flag' | sed '/^$/d')

          if [[ -z "$WHATS_NEW" ]]; then
            WHATS_NEW="No detailed updates were provided in the PR."
          fi

          echo "version=$VERSION" >> $GITHUB_ENV
          echo "feature_title=$FEATURE_TITLE" >> $GITHUB_ENV
          echo "whats_new<<EOF" >> $GITHUB_ENV
          echo "$WHATS_NEW" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Generate Release Notes
        id: generate_notes
        run: |
          VERSION="${{ env.version }}"
          FEATURE_TITLE="${{ env.feature_title }}"
          WHATS_NEW="${{ env.whats_new }}"

          cat > release_notes.md << EOF
          # Release Notes - Version $VERSION: $FEATURE_TITLE
          ## Overview
          This release includes updates based on the merged pull request.

          ## Version $VERSION: $FEATURE_TITLE
          ### What's New:
          $WHATS_NEW

          ---
          ## How to Use
          ### Admins:
          - Log in to create elections under **New Election**.
          - Configure settings, upload candidates, and share the generated link.
          - Monitor results in the **Elections Dashboard**.

          ### Voters:
          - Click the election link during voting hours.
          - Select candidate(s) and submit.

          ---
          ## Footer
          &copy; $(date +"%Y") Resolve. All rights reserved.  
          [View All Release Notes](https://github.com/hngprojects/E-Vote-FE/releases)
          EOF

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: "v${{ env.version }}"
          name: "E-Vote v${{ env.version }}: ${{ env.feature_title }}"
          bodyFile: release_notes.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
