run-name: Branch Tagging
on:
  push:
    branches:
      - main
permissions:
  contents: write  # Required for pushing tags and creating releases  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_sha: ${{ secrets.GITHUB_SHA }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          tag_prefix : v
      - name: Parse PR for Release Information
        id: parse_pr
        run: |
          # Extract release title from PR
          if [[ "${{ github.event.pull_request.title }}" =~ Release.*:\ *(.*) ]]; then
            FEATURE_TITLE="${BASH_REMATCH[1]}"
          else
            FEATURE_TITLE="Production Update"
          fi
          # Parse PR body for "What's New" section
          PR_BODY="${{ github.event.pull_request.body }}"
          WHATS_NEW=""
          if [[ "$PR_BODY" =~ '## What'\''s New'([\s\S]*?)($|##) ]]; then
            WHATS_NEW="${BASH_REMATCH[1]}"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "feature_title=$FEATURE_TITLE" >> $GITHUB_OUTPUT
          # Format the what's new content to a file
          echo "$WHATS_NEW" > whats_new.txt
