name: Milestone Closure

on:
  milestone:
    types: [closed]


permissions:
  contents: write
  issues: write

jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug - Check if event triggers
        run: echo "Workflow triggered by milestone closure, push, or manual run."

      - name: Create Release Notes
        uses: docker://decathlon/release-notes-generator-action:2.0.1
        env:
          TOKEN: ${{ secrets.TOKEN }}
          OUTPUT_FOLDER: temp_release_notes
          USE_MILESTONE_TITLE: "true"
